/** The reference pages (`docs/reference/`) are generated from the code: they must equal what `bun run docs:gen` writes. */
import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { defaults } from "../src/config.ts";
import { usageText } from "../src/usage.ts";
import { installerEnv, renderReference } from "../scripts/docs/gen.ts";

const ROOT = join(import.meta.dir, "..");
const pages = renderReference();

describe("generated reference pages", () => {
  test("there are pages, and rendering twice gives the same text", () => {
    expect(Object.keys(pages).length).toBeGreaterThanOrEqual(7);
    expect(renderReference()).toEqual(pages);
  });

  test.each(Object.keys(pages))("%s is up to date", (path) => {
    const file = join(ROOT, path);
    if (!existsSync(file)) throw new Error(`${path} is missing: run \`bun run docs:gen\` and commit the result`);
    if (readFileSync(file, "utf8") !== pages[path]) throw new Error(`${path} is out of date with the code: run \`bun run docs:gen\` and commit the result`);
  });

  test.each(Object.entries(pages))("%s: frontmatter, generated line, freshness comment", (_path, text) => {
    expect(text).toMatch(/^---\ntitle: ".+"\ndescription: ".+"\n---\n/);
    expect(text).toContain("<!-- Generated by `bun run docs:gen` from");
    expect(text).toMatch(/<!-- Keeping this file fresh: generated; run bun run docs:gen after changing .+ -->\n$/);
  });

  test.each(Object.entries(pages))("BUG-555/%s: the generated note is an HTML comment, not text the site shows its readers", (_path, text) => {
    const body = text.replace(/^---\n[\s\S]*?\n---\n/, "").replace(/<!--[\s\S]*?-->/g, "");
    expect(body).not.toMatch(/Generated by|Do not edit by hand/);
    expect(text).toMatch(/^---\n[\s\S]*?\n---\n\n<!-- Generated by `bun run docs:gen` from .+\. Do not edit by hand\. -->\n/);
  });

  test("BUG-553/the usage text starts as the real --help does, `gluon <version> — …`, with the version left as a placeholder", () => {
    const cli = pages["docs/reference/cli.md"]!;
    expect(cli).toContain("\ngluon <version> — ");
    expect(cli).not.toMatch(/^gluon — /m);
    expect(usageText(defaults(), "1.0.0").split("\n")[0]).toMatch(/^gluon 1\.0\.0 — /);
  });

  test.each(Object.entries(pages))("%s: no absolute home path, no secret-looking string", (_path, text) => {
    const home = homedir();
    expect(text).not.toContain(home);
    expect(text).not.toMatch(/\/(home|Users)\/[\w.-]+\//);
    expect(text).not.toMatch(/[A-Za-z]:\\Users\\/);
    expect(text).not.toMatch(/\b(sk-[A-Za-z0-9_-]{16,}|AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{20,}|xox[bap]-[A-Za-z0-9-]{10,}|AIza[0-9A-Za-z_-]{30,})/);
  });

  test("internal GLUON_* variables are not documented", () => {
    for (const name of ["GLUON_SELF", "GLUON_EVENTS", "GLUON_HANDOFF", "GLUON_RESUMED", "GLUON_BUILD", "GLUON_TEST_"]) expect(pages["docs/reference/env.md"]).not.toContain(name);
  });

  test("the installer variables are read from the installers' headers", () => {
    const sh = installerEnv(readFileSync(join(ROOT, "install.sh"), "utf8"));
    const ps = installerEnv(readFileSync(join(ROOT, "install.ps1"), "utf8"));
    expect(Object.keys(sh).sort()).toEqual(["GLUON_INSTALL_DIR", "GLUON_RELEASE_URL", "GLUON_VERSION"]);
    expect(Object.keys(ps).sort()).toEqual(["GLUON_ADD_TO_PATH", "GLUON_INSTALL_DIR", "GLUON_RELEASE_URL", "GLUON_VERSION"]);
  });
});
