/**
 * Writes the reference pages of the docs site (`docs/reference/`) from the code, so they cannot go stale:
 * `bun run docs:gen`. `renderReference()` is pure (path → content; no clock, no network, no home path) and
 * `test/docs-gen.test.ts` compares it with the committed files. What code cannot say (a key's meaning, a
 * flag's purpose) is a short description next to the name here; a name with none makes the render throw,
 * so a new flag, key or route cannot ship undocumented.
 *
 * Pages: docs/reference/index.md, docs/reference/cli.md, docs/reference/config.md,
 * docs/reference/routing-yaml.md, docs/reference/env.md, docs/reference/models.md,
 * docs/reference/pricing-sources.md.
 *
 * Importing this module starts nothing (it never loads `src/main.tsx`).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { configPath, DEFAULT_ORDER, defaults, ROUTES, type Route } from "../../src/config.ts";
import { PRICING_HELP } from "../../src/cost/pricing-update.ts";
import { LAUNCH_REFRESH_AFTER_MS, MODELS_DEV_URL, OPENROUTER_API_URL } from "../../src/cost/refresh.ts";
import { MAX_CHANGED_FRACTION, MAX_PRICE_RATIO, TABLE_NAMES, tableFile, type TableName } from "../../src/cost/table-schema.ts";
import { HANDOFF_GLOBAL_KEYS, HANDOFF_KEYS, HANDOFF_YAML, ON_CLEAR, ON_COMPACT, ON_EXIT } from "../../src/handoff.ts";
import { DEFAULT_MODELS, HARNESS_INFO, HARNESSES, installMethods, PROVIDER_IDS, PROVIDERS, type Conn, type Harness, type InstallPlatform, type ModelEntry } from "../../src/harnesses.ts";
import { DEFAULT_ROUTING_YAML } from "../../src/routing-config.ts";
import { STATS_HELP } from "../../src/stats.ts";
import { UPDATE_HELP } from "../../src/update/update.ts";
import { CLI_OPTIONS, HINT_COMMANDS, usageText } from "../../src/usage.ts";

const ROOT = join(import.meta.dir, "../..");

/** Every page, by its path from the repository root. */
export const PAGES = {
  index: "docs/reference/index.md",
  cli: "docs/reference/cli.md",
  config: "docs/reference/config.md",
  routing: "docs/reference/routing-yaml.md",
  env: "docs/reference/env.md",
  models: "docs/reference/models.md",
  pricing: "docs/reference/pricing-sources.md",
} as const;

const read = (path: string): string => readFileSync(join(ROOT, path), "utf8");
/** A table cell: no pipes, no line breaks. */
const cell = (s: string | undefined): string => (s ?? "").replace(/\s*\n\s*/g, " ").replaceAll("|", "\\|");
const table = (head: string[], rows: string[][]): string => [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`, ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`)].join("\n");
const code = (s: string): string => `\`${s}\``;
const fence = (lang: string, text: string): string => `\`\`\`${lang}\n${text.replace(/\n$/, "")}\n\`\`\``;
const need = <T>(map: Record<string, T>, key: string, what: string): T => {
  if (!(key in map)) throw new Error(`scripts/docs/gen.ts: ${what} "${key}" has no description: add it next to the others`);
  return map[key]!;
};

/** Starlight frontmatter, the "generated" note (an HTML comment: readers of the site don't need it), the body and the freshness comment every Markdown file ends with. */
function page(title: string, description: string, sources: string[], body: string): string {
  return `---
title: ${JSON.stringify(title)}
description: ${JSON.stringify(description)}
---

<!-- Generated by \`bun run docs:gen\` from ${sources.join(", ")}. Do not edit by hand. -->

${body.trim()}

<!-- Keeping this file fresh: generated; run bun run docs:gen after changing ${sources.join(", ")}. -->
`;
}

// ---------------------------------------------------------------- cli.md

const FLAG_DOC: Record<string, string> = {
  launch: "Skip the chat and launch this agent directly (`--model` is required; the prompt follows `--`).",
  model: "The model for `--launch`: an id from the catalog that the agent's connection serves.",
  effort: "The effort for `--launch`, one of the levels the model takes.",
  mode: "With `--launch`: `build` (the default), `explore` (read-only) or `plan` (the agent's plan mode).",
  "dry-run": "With `--launch`: print the command instead of running it.",
  all: "With `gluon resume` and `gluon sessions`: every directory's saved sessions, not just this one's.",
  force: "With `gluon resume` and `gluon sessions --delete`: even while another Gluon has the workspace open.",
  delete: "With `gluon sessions`: delete one saved workspace by id (asks first).",
  demo: "Open the same UI with a scripted intake agent (no API calls).",
  help: "Print the usage text and exit.",
  version: "Print Gluon's version and exit.",
};

/** Commands handled before the config loads (`src/main.tsx`) are not in `SUBCOMMANDS`; `usageText` lists them all. */
const COMMAND_DOC: Record<string, string> = {
  setup: "Connect your coding agents (API key or subscription).",
  connect: "Connect or reconnect one agent: `gluon connect <harness>`.",
  install: "Install missing agents with their official installers; shows each command and runs it only if you say so.",
  sessions: "List the saved sessions (workspaces) of every directory; `--delete <id>` removes one.",
  resume: "Reopen a saved workspace: its sessions pick up where they were.",
  routing: "`check` validates routing.yaml, `path` prints where it is, `default` prints the one this Gluon ships.",
  brain: "Show the intake agent order (`brain.order`) and the step in use.",
  doctor: "Check every agent, model and brain step for real (calls the models: it can cost money).",
  uninstall: "Remove Gluon's config, saved keys and files (and the binary, on a standalone install).",
  "cost-report": "What Gluon's own cost figures were audited against (no model calls).",
  pricing: "`pricing update` rebuilds the price tables from your installed agents and Claude's public model catalog.",
  update: "Install the latest Gluon release in place of this one, once its signature and checksum verify; `--check` only says whether there is one.",
  stats: "What Gluon recorded about your launched sessions (a local file): time and cost per agent, model, day or repository, the newest sessions, one session in full, a read-only SQL query.",
};

function cliPage(): string {
  const names = HINT_COMMANDS;
  // The real `--help` starts `gluon 1.0.0 — …`: the page names no version, so it shows the literal `<version>`.
  const usage = usageText(defaults(), "<version>");
  const flags = Object.entries(CLI_OPTIONS).map(([name, o]) => {
    const short = "short" in o ? code(`-${o.short}`) : "";
    return [code(`--${name}`), short, o.type === "string" ? "value" : "flag", need(FLAG_DOC, name, "flag")];
  });
  const commands = names.map((n) => [code(`gluon ${n}`), need(COMMAND_DOC, n, "command")]);
  // `gluon pricing update` names the state directory it keeps the tables in: show the Linux default, not this machine's.
  const pricing = PRICING_HELP.replace(/\([^()\n]*[\\/]gluon[\\/]tables\)/, "(`~/.local/state/gluon/tables`; `%LOCALAPPDATA%\\gluon\\tables` on Windows)");
  const body = `
## Usage

\`gluon --help\` prints this (the agent list at the end is the built-in catalog).

${fence("text", usage)}

## Commands

${table(["Command", "What it does"], commands)}

A first word that is none of these starts a session with it as the first message: quote it, as in \`gluon "fix the failing test"\`.

## Flags

${table(["Flag", "Short", "Takes", "Meaning"], flags)}

A prompt that starts with \`-\` goes after \`--\`: \`gluon --launch <harness> --model <m> -- "- the prompt"\`. \`gluon sessions --delete <id>\` also takes \`--yes\` (delete without asking, for use without a terminal), and \`gluon uninstall\` takes \`--yes\` too.

## gluon pricing update

${fence("text", pricing)}

## gluon stats

${fence("text", STATS_HELP)}

## gluon update

${fence("text", UPDATE_HELP)}
`;
  return page("Command line", "Every gluon command and flag, from the program's own usage text.", ["src/usage.ts", "src/cost/pricing-update.ts", "src/stats.ts", "src/update/update.ts"], body);
}

// ---------------------------------------------------------------- config.md

const TOP_KEYS: Record<string, string> = {
  connections: "How each agent is connected: a subscription, or an API-key provider (OpenCode: several providers).",
  bedrock: "The AWS profile and region every Amazon Bedrock use goes through.",
  verified: "Written by Gluon: `harness/connection/model-id` → the date a check reached it.",
  checked: "Written by Gluon: `harness/connection` → the date its models were last checked.",
  unreached: "Written by Gluon: `harness/connection/model-id` → the date a check definitively failed to reach it (hidden from the offer).",
  brain: "Where the intake agent runs: an ordered list of steps; the first working one is used.",
  handoff: "What happens around an agent's session in Gluon's frame: its end, `/clear`, `/compact`, the home key and the mouse.",
  cost: "Gluon's own cost figures.",
  analytics: "`on` (default) records one row per launched session in `<state dir>/analytics.db`, queried with `gluon stats`; `off` stops recording.",
  updates: "`auto` (default) installs a new Gluon release by itself at start, after checking its signature and checksum (it runs from the next start); `notify` only says one exists; `off` never checks. GitHub is asked once a day while Gluon is up to date, and at each start while a newer release is known. `GLUON_UPDATES` wins over it.",
};
/** Keys of `defaults()` that are derived or catalog facts, not config.yaml keys. */
const DERIVED_KEYS = new Set(["models", "agents"]);

const ROUTE_DOC: Record<Route, string> = {
  "claude-plan": "Your Claude plan, through the `claude` binary (Agent SDK).",
  "chatgpt-plan": "Your ChatGPT plan, through `codex app-server`.",
  "anthropic-api": "The Anthropic API with your key.",
  "openai-api": "The OpenAI API with your key.",
  bedrock: "Amazon Bedrock, with your AWS profile and region.",
  openrouter: "OpenRouter with your key.",
};

const HANDOFF_DOC: Record<string, string> = {
  on_exit: "`return`: the session closes when the agent exits and the sessions home shows. `quit`: Gluon exits with the agent's code (the last session).",
  on_clear: "`ask`: the agent's `/clear` asks whether to end the session. `stay`: the agent's own `/clear`.",
  on_compact: "`ask`: `/compact` (and auto-compaction where possible) asks whether to end the session instead. `stay`: the agent compacts.",
  key: "The key that opens the session menu from anywhere in the agent (←/→ switch; again: the sessions home). One of `ctrl+\\`, `ctrl+]`, `ctrl+^`, `ctrl+_`.",
  mouse_capture: "Clicks on the sessions home's rows; the wheel scrolls the home chat, and a session's frame when its agent doesn't use the mouse. `false`: never.",
};
const HANDOFF_VALUES: Record<string, readonly string[]> = { on_exit: ON_EXIT, on_clear: ON_CLEAR, on_compact: ON_COMPACT };

const COST_DOC: Record<string, string> = {
  audit: "`off` keeps no audit ledger on disk (the figures shown are unaffected).",
  antigravity_statusline: "`on` lets Gluon set Antigravity's status line, which is where its context comes from (Antigravity has no cost).",
};

const snake = (s: string): string => s.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
const yamlValue = (v: unknown): string => (typeof v === "boolean" ? String(v) : String(v));

function configPage(): string {
  const d = defaults();
  const keys = Object.keys(d).filter((k) => !DERIVED_KEYS.has(k));
  const paths = [
    ["Linux, macOS", code(configPath({}, "linux", "~"))],
    ["Windows", code(configPath({ APPDATA: "%APPDATA%" }, "win32", "~"))],
    ["Anywhere", `${code("GLUON_CONFIG")} (a path; a relative one is taken from the directory you start Gluon in) wins; ${code("XDG_CONFIG_HOME")} (an absolute path; a relative one is ignored) moves the directory. routing.yaml and the saved keys (${code(".env")}) live next to it.`],
  ];
  const handoffKeys = [...HANDOFF_KEYS, ...HANDOFF_GLOBAL_KEYS];
  const handoffRows = handoffKeys.map((k) => {
    const value = (d.handoff as unknown as Record<string, unknown>)[k];
    return [code(k), code(yamlValue(value)), need(HANDOFF_DOC, k, "handoff key"), HANDOFF_VALUES[k] ? HANDOFF_VALUES[k]!.map(code).join(", ") : k === "mouse_capture" ? `${code("true")}, ${code("false")}` : "a key name"];
  });
  const costRows = Object.entries(d.cost).map(([k, v]) => [code(`cost.${snake(k)}`), code(v ? "on" : "off"), need(COST_DOC, snake(k), "cost key")]);
  const steps = DEFAULT_ORDER.map((s, i) => [String(i + 1), code(s.route), code(s.model), s.effort ? code(s.effort) : "default"]);
  const conn = (h: Harness) => {
    const info = HARNESS_INFO[h];
    if (info.multiProvider) return `${code("providers")}: a list of ${info.providers.map(code).join(", ")}`;
    const api = info.providers.map(code).join(", ");
    return `${code("auth: subscription")}${info.subscription ? ` (${info.subscription.plan})` : ""}, or ${code("auth: api")} with ${code("provider")}: ${api}`;
  };
  const body = `
## Where it is

${table(["Where", "Path"], paths)}

Gluon writes it for you (\`gluon setup\`, \`gluon connect\`); everything below can also be edited by hand. A file that isn't valid YAML stops Gluon with its path and line.

## Top-level keys

${table(["Key", "Meaning"], keys.map((k) => [code(k), need(TOP_KEYS, k, "config key")]))}

A \`models:\` key from earlier versions is ignored: the model catalog is built in (see [Models](models.md)).

## connections

One entry per agent, under \`connections.<agent>\`:

${table(["Agent", "Connection"], HARNESSES.map((h) => [code(h), conn(h)]))}

## bedrock

\`bedrock.profile\` and \`bedrock.region\` set the AWS profile and region. Unset, Gluon uses \`AWS_PROFILE\`, then \`AWS_REGION\` or \`AWS_DEFAULT_REGION\`, then the \`region\` of the profile in your AWS config (\`$AWS_CONFIG_FILE\`, else \`~/.aws/config\`), then \`us-east-1\`.

## brain

\`brain.order\` is the list of steps the intake agent may run on; \`brain.active\` is the step in use (Gluon sets it). A step is \`route\`, \`model\` and optionally \`effort\` (\`low\`, \`medium\`, \`high\`, \`xhigh\`, \`max\`). The routes:

${table(["Route", "Where the intake agent runs"], ROUTES.map((r) => [code(r), need(ROUTE_DOC, r, "route")]))}

The default order:

${table(["#", "Route", "Model", "Effort"], steps)}

## handoff

${table(["Key", "Default", "Meaning", "Values"], handoffRows)}

Per-agent values go under \`handoff.agents.<agent>\` (${HANDOFF_KEYS.map(code).join(", ")}) and win over the ones above. The section Gluon adds to an existing config file:

${fence("yaml", HANDOFF_YAML)}

## cost

${table(["Key", "Default", "Meaning"], costRows)}
`;
  return page("config.yaml", "Every key of Gluon's config file, with its default.", ["src/config.ts", "src/handoff.ts"], body);
}

// ---------------------------------------------------------------- routing-yaml.md

function routingPage(): string {
  const body = `
\`routing.yaml\` sits next to [config.yaml](config.md) and decides which agent, model and effort runs a session, and what the intake agent is told about your preferences. Gluon writes this file when there is none and replaces it with a newer default only while you haven't edited it. \`gluon routing check\` validates yours, \`gluon routing path\` says where it is and \`gluon routing default\` prints the file below.

${fence("yaml", DEFAULT_ROUTING_YAML)}
`;
  return page("routing.yaml", "The routing file Gluon ships as its default, verbatim.", ["src/routing.yaml"], body);
}

// ---------------------------------------------------------------- env.md

/** The `Environment:` block of an installer's header comment: name → text (continuation lines joined). */
export function installerEnv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  const lines = text.replace(/\r/g, "").split("\n");
  const start = lines.findIndex((l) => /^[#\s]*Environment:\s*$/.test(l));
  if (start === -1) return out;
  let current: string | undefined;
  for (const raw of lines.slice(start + 1)) {
    const line = raw.replace(/^#/, "");
    const m = line.match(/^\s+(GLUON_[A-Z_]+)\s{2,}(.*)$/);
    if (m) {
      current = m[1]!;
      out[current] = m[2]!.trim();
    } else if (current && /^\s{10,}\S/.test(line)) out[current] += ` ${line.trim()}`;
    else break;
  }
  return out;
}

function envPage(): string {
  const providers = PROVIDER_IDS.filter((p) => PROVIDERS[p].env).map((p) => {
    const info = PROVIDERS[p];
    const agents = HARNESSES.filter((h) => HARNESS_INFO[h].providers.includes(p)).map((h) => HARNESS_INFO[h].label);
    return [code(info.env!), info.label, agents.join(", "), info.keyUrl ?? ""];
  });
  const sh = installerEnv(read("install.sh"));
  const ps = installerEnv(read("install.ps1"));
  const names = [...new Set([...Object.keys(sh), ...Object.keys(ps)])].sort();
  const plain = (t: string | undefined) => (t ?? "n/a").replace(/<([^<>\s]+)>/g, "&lt;$1&gt;");
  const installer = names.map((n) => [code(n), plain(sh[n]), plain(ps[n])]);
  const body = `
## API keys

Gluon takes a provider's key from the \`.env\` file next to the config (what \`gluon setup\` saved) or, failing that, from the environment. A launched agent gets only its model's provider key. Subscriptions use each agent's own login and need no variable.

${table(["Variable", "Provider", "Used by", "Create a key at"], providers)}

Amazon Bedrock takes no key: it uses your AWS profile and region (below).

## Config location

${table(["Variable", "Meaning"], [
    [code("GLUON_CONFIG"), "Path of config.yaml (routing.yaml and the saved keys move with it); a relative path is made absolute from the directory Gluon starts in."],
    [code("XDG_CONFIG_HOME"), "Moves the config directory: `$XDG_CONFIG_HOME/gluon/config.yaml`; a relative path is ignored, as the XDG spec says. On Windows the default is `%APPDATA%`."],
  ])}

## Updates

${table(["Variable", "Meaning"], [
    [code("GLUON_UPDATES"), "`auto`, `notify` or `off`: wins over the config key `updates` (for CI and managed machines). Anything else is ignored."],
  ])}

## Amazon Bedrock

Used when \`bedrock.profile\` or \`bedrock.region\` is unset in [config.yaml](config.md):

${table(["Variable", "Meaning"], [
    [code("AWS_PROFILE"), "The AWS profile for Bedrock."],
    [code("AWS_REGION"), "The region (wins over `AWS_DEFAULT_REGION`); when neither is set, the profile's `region` in your AWS config, else `us-east-1`."],
    [code("AWS_CONFIG_FILE"), "Where Gluon reads the AWS config's `region` from, instead of `~/.aws/config` (that key only)."],
    [code("AWS_DEFAULT_REGION"), "The region, when `AWS_REGION` is not set."],
  ])}

## Installer

Read from the header comments of \`install.sh\` (Linux, macOS) and \`install.ps1\` (Windows):

${table(["Variable", "install.sh", "install.ps1"], installer)}
`;
  return page("Environment variables", "The environment variables Gluon and its installers read.", ["src/harnesses.ts", "src/config.ts", "src/update/update.ts", "install.sh", "install.ps1"], body);
}

// ---------------------------------------------------------------- models.md

const PLATFORM_LABEL: Record<InstallPlatform, string> = { posix: "Linux, macOS, WSL", win32: "Windows" };

function connLabel(h: Harness, c: Conn): string {
  return c === "plan" ? (HARNESS_INFO[h].subscription?.plan ?? "plan") : PROVIDERS[c].label;
}

function modelRow(h: Harness, m: ModelEntry, conns: Conn[]): string[] {
  const efforts = m.efforts.length ? m.efforts.map(code).join(", ") + (m.effortConns ? ` (${m.effortConns.map((c) => connLabel(h, c)).join(", ")} only)` : "") : "none";
  const notes = [m.note];
  if (m.current) notes.push(`follows the latest release (${m.current} today)`);
  if (m.optIn) notes.push(`opt-in: ${code(m.optIn)} in routing.yaml${m.sharesDataWith ? `; ${m.sharesDataWith} receives the session's code and prompts` : ""}`);
  return [m.label, code(m.id), ...conns.map((c) => (m.ids[c] ? code(m.ids[c]!) : "—")), efforts, m.efforts.length ? code(m.defaultEffort ?? "medium") : "—", notes.join("; ")];
}

function modelsPage(): string {
  const sections = HARNESSES.map((h) => {
    const info = HARNESS_INFO[h];
    const models = DEFAULT_MODELS[h];
    const conns = (["plan", ...PROVIDER_IDS] as Conn[]).filter((c) => models.some((m) => m.ids[c]));
    const install = (Object.keys(PLATFORM_LABEL) as InstallPlatform[]).flatMap((p) =>
      installMethods(h, p === "win32" ? "win32" : "linux").map((m) => [PLATFORM_LABEL[p], code(m.command), m.host, m.note ?? ""]),
    );
    const modes = (["explore", "plan"] as const).map((mode) => {
      const l = info.modes[mode];
      return `${code(mode)}: ${l.unavailable ? `unavailable (${l.unavailable})` : l.note ?? (l.typed ? `typed as ${code(l.typed)} once the agent is up` : "supported")}`;
    });
    return `
## ${info.label}

${info.note}

- Binary: ${code(info.binary)} (${info.vendor})
- Connections: ${[info.subscription ? `${info.subscription.plan} (subscription)` : undefined, ...info.providers.map((p) => PROVIDERS[p].label)].filter(Boolean).join(", ")}
- Modes besides build: ${modes.join("; ")}

${table(["Model", "Id", ...conns.map((c) => connLabel(h, c)), "Efforts", "Default effort", "Notes"], models.map((m) => modelRow(h, m, conns)))}

Install (official methods, the vendor's recommended first; Gluon shows the command and runs it only on an explicit "Run it"):

${table(["Where", "Command", "Downloads from", "Note"], install)}
`;
  });
  const body = `
Gluon's built-in catalog: facts about each model, not configuration. The **Id** is what the intake agent proposes and \`--launch --model\` takes; the connection columns are the id each connection's API or plan uses (— : not served there). Which of these the intake agent may propose is decided per machine by a check (\`gluon doctor\`); how it decides is in [Connections](../guides/connections.md#how-gluon-decides-a-model-is-reachable).
${sections.join("")}`;
  return page("Models", "The built-in model catalog: ids per connection, efforts and install methods for every agent.", ["src/harnesses.ts"], body);
}

// ---------------------------------------------------------------- pricing-sources.md

/** Per table: what it holds, where it is built from on the user's machine, and the code that builds it. A new table name fails the typecheck until it is described. */
const TABLE_SOURCES: Record<TableName, { source: string; builder: string }> = {
  modelsdev: {
    source: `The public models.dev catalog (${code(MODELS_DEV_URL)}): prices and context limits for the models Gluon offers and every priced model of the providers OpenCode uses. Each ${code("openrouter/*")} price is OpenRouter's own (${code(`${OPENROUTER_API_URL}/models`)} and the per-model ${code("/endpoints")}, what OpenRouter bills); models.dev's row is kept beside it where they differ.`,
    builder: "src/cost/modelsdev-catalog.ts",
  },
  "claude-catalog": {
    source: "The installed Claude Code binary alone, read as bytes and never run: its model catalog and the fast-mode rows of its price function. Anthropic's published catalog has no prices.",
    builder: "src/cost/claude-catalog.ts",
  },
  "codex-windows": { source: `The installed Codex: ${code("codex debug models")} (no model is called).`, builder: "src/cost/codex-catalog.ts" },
  "grok-models": {
    source: "The model list embedded in the installed Grok Build binary, read as bytes. Its prices are a marked seed from models.dev. A model the binary lacks gets the window of the observed table below, else none.",
    builder: "src/cost/grok-catalog.ts",
  },
  "grok-observed-windows": { source: "The only table in the repository: a window Grok showed for a model its binary does not list yet, with the evidence. Written by hand.", builder: "by hand" },
};

function pricingPage(): string {
  const rows = TABLE_NAMES.map((name: TableName) => {
    const { source, builder } = TABLE_SOURCES[name];
    return [code(tableFile(name)), source, builder === "by hand" ? builder : code(builder)];
  });
  const minutes = LAUNCH_REFRESH_AFTER_MS / 60_000;
  const body = `
Gluon's own cost and context figures are calculated from price and window tables that Gluon builds on your machine. No built table ships in the repository or in a release; the one hand-written table below is the exception. The harnesses' own reports only audit the figures.

${table(["Table", "Where it comes from", "Built by"], rows)}

## When they are built

- **At Gluon's start**, in the background (the first screen never waits for it): the models.dev catalog and OpenRouter's listing with the endpoints of the models Gluon offers on it.
- **At each harness launch**, in the background: the launched harness's own table, read from its installed binary (again only when the binary's version changes), the network tables when the last refresh is more than ${minutes} minutes old, and the launched ${code("openrouter/*")} model's row.
- **On demand**: ${code("gluon pricing update")} runs the same refresh in the foreground and prints what it wrote.

The calls to models.dev and OpenRouter are plain unauthenticated requests, with a timeout and a size cap. They cannot be turned off. Offline, or when a source fails, Gluon keeps the last stored table, whatever its age. A session launched before any table exists is priced when the tables land, and a session keeps the tables it was priced with.

## Where they are kept

In ${code("<state>/gluon/tables/")}, one file per table, in a private directory. Every table is checked against an allowlist of keys and shapes before it is read or kept; one that fails is refused. A large move is not: when more than ${MAX_CHANGED_FRACTION * 100}% of a table's prices change, one price moves more than ${MAX_PRICE_RATIO}x or a model disappears, Gluon takes the table and logs the move in the audit ledger. ${code("gluon uninstall")} removes the directory.

${code("gluon cost-report")} lists each table with its source, date, when it was fetched, how many requests it priced and the refreshes that changed it.
`;
  return page("Pricing sources", "Where each price and window table comes from, and when Gluon builds it on your machine.", ["src/cost/table-schema.ts", "src/cost/refresh.ts", "src/cost/tables.ts"], body);
}

// ---------------------------------------------------------------- index.md

function indexPage(): string {
  const link = (p: string) => p.replace("docs/reference/", "");
  const body = `
Everything here is generated from the code by \`bun run docs:gen\`, so it matches the version of Gluon it was built from.

- [Command line](${link(PAGES.cli)}): every command and flag.
- [config.yaml](${link(PAGES.config)}): every key, with its default.
- [routing.yaml](${link(PAGES.routing)}): the routing file Gluon ships.
- [Environment variables](${link(PAGES.env)}): API keys, config location, AWS, installer.
- [Models](${link(PAGES.models)}): the built-in catalog, ids per connection, efforts, install methods.
- [Pricing sources](${link(PAGES.pricing)}): where the price and window tables come from.
`;
  return page("Reference", "Generated reference for Gluon's command line, configuration, models and pricing tables.", ["scripts/docs/gen.ts"], body);
}

/** Every reference page: repository path → content. Pure and deterministic. */
export function renderReference(): Record<string, string> {
  return {
    [PAGES.index]: indexPage(),
    [PAGES.cli]: cliPage(),
    [PAGES.config]: configPage(),
    [PAGES.routing]: routingPage(),
    [PAGES.env]: envPage(),
    [PAGES.models]: modelsPage(),
    [PAGES.pricing]: pricingPage(),
  };
}

if (import.meta.main) {
  for (const [path, content] of Object.entries(renderReference())) {
    const full = join(ROOT, path);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
    console.log(`wrote ${path}`);
  }
}
